version: '3'
services:
  ui:
    build:
      context: ../ui
      dockerfile: ../base.node.Dockerfile
    volumes:
      - ../ui:/app
    expose:
      - '4200'
      - '3000'
    ports:
      - 4200:4200
    environment:
      NODE_ENV: ${NODE_ENV}
    networks:
      - backend-net
  api:
    restart: always
    build:
      context: ../api
      dockerfile: ../base.node.Dockerfile
    volumes:
      - ../api:/app
    expose:
      - '3000'
    ports:
      - 3000:3000
    environment:
      NODE_ENV: ${NODE_ENV}
    networks:
      - backend-net
  db:
    image: postgres
    volumes:
      - ./volumes/$POSTGRES_DB:/var/lib/postgresql
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - backend-net
networks:
  backend-net:
    driver: bridge
