version: "3"
services:
  db:
    image: postgres
    restart: always
    volumes:
      - ./volumes/dev_db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: dev_db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
